### ISSUE TITLE
单独运行获取依赖出错

### ISSUE THREAD

**Issue by nagaame** [JiangInk/market_monitor#2]
使用`go run main.go`提示
 cannot find package "github.com/JiangInk/market_monitor/extend/conf" in any of:
使用`dep init -v`提示
init failed: unable to solve the dependency graph: Solving failure: No versions of github.com/JiangInk/market_monitor met constraints:

go版本 1.11.1
系统macOS

请问咋解决呢??

**Comment by ErikJiang** [comment]
:sweat_smile: 抱歉哦，我之前的 import 路径有所改变，没来得及修改，现在已经修改并提交，你需要 pull 一下~
@nagaame

**Comment by nagaame** [comment]
@ErikJiang 好的☺️

**Comment by novice87** [comment]
我这边也遇到这个问题:(， 是不是漏了什么操作？
mac os  go version go1.12 darwin/amd64

```go run main.go```

> main.go:7:2: cannot find package "github.com/ErikJiang/market_monitor/extend/conf" in any of:
> 	/Users/wkang/codes/hash.tech/go/src/market_monitor/app/src/vendor/github.com/ErikJiang/market_monitor/extend/conf (vendor tree)
> ....
> 

```dep init -v```

> init failed: unable to solve the dependency graph: Solving failure: No versions of github.com/ErikJiang/market_monitor met constraints:
> 	master: Could not introduce github.com/ErikJiang/market_monitor@master due to multiple problematic subpackages:
> 	Subpackage github.com/ErikJiang/market_monitor/extend/email is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/extend/jwt is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/extend/redis is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/models is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/extend/code is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/extend/conf is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/middleware is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/router is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/docs is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/extend/utils is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/extend/api is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/service is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/extend/validator is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/schedule is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/controller/v1 is missing. (Package is required by (root).)	Subpackage github.com/ErikJiang/market_monitor/extend/logger is missing. (Package is required by (root).)

**Comment by nagaame** [comment]
@novice87 如果你是golang 1.12 然后在goland的go module打开vgo 选择系统安装的go 1.12版本
 然后进入src/app
然后输入命令
`go mod download`
`go mod tidy`
`go mod vendor`

接着build接入
`go build .`

试试看行不行
🌝

**Comment by novice87** [comment]
> @novice87 如果你是golang 1.12 然后在goland的go module打开vgo 选择系统安装的go 1.12版本
> 然后进入src/app
> 然后输入命令
> `go mod download`
> `go mod tidy`
> `go mod vendor`
> 
> 接着build接入
> `go build .`
> 
> 试试看行不行
> 🌝

可以了，感谢！！ 新手刚接触Go，不太熟悉，感谢楼主的指点和开源。:)
