### ISSUE TITLE
docker-compose up -d 运行出错

### ISSUE THREAD

**Issue by xx19941215** [JiangInk/market_monitor#3]
![image](https://user-images.githubusercontent.com/10104328/51108151-1d41f400-182c-11e9-872e-e52ffa389d6f.png)

**Comment by ErikJiang** [comment]
你好，在运行`docker-compose up -d`之前，需要先在`app/src/`目录执行`go mod vendor`，请先查看：[详细文档](https://github.com/ErikJiang/market_monitor/wiki/DockerBuildTutorials#%E5%A4%84%E7%90%86%E6%9E%84%E5%BB%BA%E8%BF%87%E7%A8%8B%E7%9A%84%E4%BE%9D%E8%B5%96%E5%8C%85%E9%97%AE%E9%A2%98)，另外我将会在`README`中补充，谢谢反馈~

**Comment by xx19941215** [comment]
@ErikJiang 这个go mod vendor的动作没办法在构建之后容器内执行吗，这样我就不用在安装go环境了 hhhh..

**Comment by ErikJiang** [comment]
如果你本地已经执行过 `go build` 或 `go run main.go`，那你在本地就已经存在一份依赖包文件的缓存，这时生成 `vendor` 目录会相对快很多，如果这个操作放在构建容器镜像过程中执行，就会涉及到镜像内依赖包文件下载的问题，会很耗时拖慢构建速度。

之前我有尝试在镜像内使用 `go mod download` 的方式，在构建过程中处理依赖问题，但是中间存在一些下载的问题，且没时间去处理，故使用`vendor`方式，如果你对 `go mod download` 的方式感兴趣，可以尝试一下。
