### ISSUE TITLE
grom:table_options , grom 应该改为 gorm

### ISSUE THREAD

**Issue by llych** [JiangInk/market_monitor#7]
app/src/models/dbSetup.go
DB.Set(
		"grom:table_options",
		"ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci",
	).AutoMigrate(&User{}, &Task{})

grom:table_options , grom 应该改为 gorm

**Comment by ErikJiang** [comment]
@llych 已更新，感谢指正，:clap:
