### ISSUE TITLE
所有包都导入了，但是build的时候提示无法加载这些包，请问是什么原因呢？

### ISSUE THREAD

**Issue by bobojx** [JiangInk/market_monitor#9]
build command-line-arguments: cannot load github.com/ErikJiang/market_monitor/extend/conf: cannot find module providing package github.com/ErikJiang/market_monitor/extend/conf

**Comment by bobojx** [comment]
![image](https://user-images.githubusercontent.com/10562738/54106238-75523c80-4410-11e9-85bc-f70ff5e99100.png)

**Comment by ErikJiang** [comment]
如果你是单独运行服务，请先 `cd market_monitor/app/src/` 目录下，再执行 `go run main.go`，这个在 readme 中有说明过
